# ===================================================================
# SpringDoc Configuration
# ===================================================================
springdoc:
  show-actuator: true
  swagger-ui:
    operationsSorter: method

# ===================================================================
# Spring Web Configuration
# ===================================================================
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# ===================================================================
