### Register User
POST {{host}}:{{port}}/user/register
Content-Type: application/json

{
  "email": "john..doe@example.com",
  "username": "johndoes",
  "name": "John",
  "surname": "Doe",
  "birthdate": "1990-05-15",
  "password": "securePassword.123"
}

