### Search Users - Basic
GET {{host}}:{{port}}/user/search/inde
### Search Users
GET {{host}}:{{port}}/user/search/admin

### Search Users - With First Page
GET {{host}}:{{port}}/user/search/admin/0

### Search Users - With First Page and Size
GET {{host}}:{{port}}/user/search/admin/0/10

### Search Users - With Second Page
GET {{host}}:{{port}}/user/search/admin/1

// TODO: Page & Size not works

