### Update User
PUT {{host}}:{{port}}/user/84a5122c-1646-4ff4-83d0-cb618418c34f
Content-Type: application/json

{
  "email": "john.updateds@example.com",
  "username": "johndoe_updated",
  "name": "John",
  "surname": "Doe Updated",
  "birthdate": "1990-05-15",
  "password": "newSecurePassword123"
}

// TODO: Update not works

