# ===================================================================
# Logger Configuration
# ===================================================================
logging:
  level:
    com.codenaiten.template.server: DEBUG

# ===================================================================
